### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-vagrant#10]
Would it be possible to support HTTPS with this setup? Or is that too far off 'basic'?  

My theme for [Black Buddha](https://black-buddha.com) is designed for HTTPS but is flexible enough to work with http. It would be great to have the option.

**Comment by joemaller** [comment]
I haven't done much of this yet, but it should be possible. 

http://httpd.apache.org/docs/current/ssl/ssl_faq.html#selfcert

**Comment by jgraup** [comment]
Thanks, I'll give this a shot.

**Comment by joemaller** [comment]
Just bumped into this hard today and could really use the HTTPS/SSL option.
