### ISSUE TITLE
Any way to salvage Vagrant instance on computer shutdown?

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-vagrant#14]
My computer froze and I was forced to restart my computer. All my vagrant boxes are in VirtualBox and in a `Powered Off` state. Is there an easy way to turn them back on like nothing happened? Or is everything lost?

**Comment by joemaller** [comment]
You should be able to just `vagrant up` and pick up where you left off, is that not working?

**Comment by jgraup** [comment]
I didn't want to do the wrong thing as this is a new platform for me. I just tested your suggestion and it's working now. So thanks again!
