### ISSUE TITLE
WP-CLI @alias without password

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-vagrant#29]
Currently I have a basic.dev box setup and an `@basic` [alias](https://wp-cli.org/blog/version-0.24.0.html#effortlessly-use-wp-cli-against-any-wordpress-install) in my `~/.wp-cli/config.yml` to point to http://basic.dev/.

```
@basic:
    ssh: vagrant@172.28.128.7/var/www/wordpress/ 
```

Outside of Vagrant I can run `wp @basic theme list` but I'm prompted for a password.

Do you have a work-around for password prompting when using an [`@alias`](https://wp-cli.org/commands/cli/alias/) outside of the vagrant box?

**Comment by joemaller** [comment]
I just read over the [wp-cli config docs](http://wp-cli.org/config/) and it doesn't look like the `ssh:` option can take additional SSH args. The way Vagrant connects internally is to reference a generated VM-specific SSH key. The `vagrant ssh` command includes something like this: 

```
-o StrictHostKeyChecking=no -o 'IdentityFile="/Users/joe/basic-wordpress-vagrant/.vagrant/machines/default/virtualbox/private_key"'
```

What you _could_ do is edit your `~/.ssh/config` file to include the key and user. A clause like the following should allow you to connect to the VM without a password:

```
Host basic-wordpress-vagrant.dev
User vagrant
IdentityFile ~/basic-wordpress-vagrant/.vagrant/machines/default/virtualbox/private_key
```

The private key is created by `vagrant up` in the hidden dot-folder for every VM. If you reuse the same paths, this should work fine across up/destroy/up cycles too.

Once SSH is configured, your `.wp-cli/config.yml` command might just be this:

```
@basic:
    ssh: basic.dev/var/www/wordpress
```

**Comment by jgraup** [comment]
This seems to be working well for me. Thanks for the help!

---

`~/.wp-cli/config.yml`

```
@basic:
    ssh: basic.dev/var/www/wordpress/
```

`~/.ssh/config`

```
Host basic.dev
    HostName basic.dev
    User vagrant
    IdentityFile ~/sites/basic.dev/.vagrant/machines/default/virtualbox/private_key
```

---

`wp @basic theme list`
