### ISSUE TITLE
Add Kint visual debugger by default

### ISSUE THREAD

**Issue by joemaller** [ideasonpurpose/basic-wordpress-vagrant#33]
I do this every time, might as well automate it. 

http://raveren.github.io/kint/

Require Kint in local wp-config.php and auto-download the library into the top level.

**Comment by jgraup** [comment]
Interesting. Do have tools that you use in conjunction with Kint, like https://wordpress.org/plugins/kint-debugger/? Also, is there a good way to show Kint output from AJAX calls? I'm guessing it's whatever method would have to allow for more persistent data or IDE integration.

**Comment by joemaller** [comment]
Hi @jgraup I've been using Kint for a really long time. I kind of "grew up" with `print_r` but Kint is just so much more comprehensive. 

Kint is for introspecting PHP stuff; data structures that the server is using to generate pages. For most Ajax, I usually just dump to the browser console with `console.log`. For exploring more complex API endpoints that require authentication or whatever, I use [Postman](https://www.getpostman.com/).

Other than having Sublime Text somewhat tricked out, I don't personally use much IDE stuff.
