### ISSUE TITLE
Update WP-CLI to 0.25.0

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-vagrant#35]
Based on the new WP-CLI release today and the fact that this project downloads the latest WordPress -- it might be a good time to update; http://wp-cli.org/blog/version-0.25.0.html

> Importantly, due to the nature of these changes, WP-CLI versions prior to 0.25.0 will be incompatible with WordPress 4.7.

_This may just require a rebuild of the basic box_ -- https://github.com/ideasonpurpose/basic-wordpress-box/blob/master/ansible/roles/wp-cli/tasks/main.yml#L5

**Comment by joemaller** [comment]
updated in the base box
