### ISSUE TITLE
No IP address added to hosts

### ISSUE THREAD

**Issue by mkjonesuk** [ideasonpurpose/basic-wordpress-vagrant#49]
After vagrant up and vagrant provision I still get this:

```
## vagrant-hostmanager-start id: 1234

value	basicwp.dev

## vagrant-hostmanager-end
````

Assume `value` should be an IP address right?

I already have vvv and a couple of other boxes running that can add to my hosts file so certain this isn't an issue with writing to the file. 

Other info - I dumped a WPEngine backup into sites as detailed in the setup guide 👍 

Please help!

**Comment by mkjonesuk** [comment]
CLOSED: After rebooting, re-provisioning and reloading it finally kicked in:

`172.28.128.3	basicwp.dev`

💯

**Comment by joemaller** [comment]
Thanks for the quick update. I was just about to say that I couldn't reproduce this
