### ISSUE TITLE
unsupported parameter for module: use_ssh_args

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-vagrant#50]
I had a coworker recently try this project and on initial `vagrant up` there seems to be a failure when doing the `Pull-sync`.

```bash
TASK: [wordpress | Pull-sync fresh WordPress onto local site directory] ******* 
failed: [default -> 127.0.0.1] => {"failed": true}
msg: unsupported parameter for module: use_ssh_args

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/myusername/main.retry

default                    : ok=9    changed=6    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Anything stand out as the culprit? 

| Name | Version     |
| :------------- | :------------- |
| [Virtual Box](https://www.virtualbox.org/ ) | 5.1.20       | Virtual Machine
| [Vagrant](https://www.vagrantup.com/ )      | 1.9.3        |
| [Ansible](https://www.ansible.com)      | 1.9.1        |
|[Basic WP](https://github.com/ideasonpurpose/basic-wordpress-vagrant/releases/tag/v0.3.6)|0.3.6|

**Comment by joemaller** [comment]
That's a very old version of Ansible. Update that and it should work.

Sidenote: Where did that copy of Ansible come from?

**Comment by jgraup** [comment]
Looks like it was an Ansible issue. I'm not sure where the original version came from but it should be up-to-date now.

> got it working - the two additional steps were: because ansible was already installed, I had to run 
> "brew unlink ansible" then to get latest: "brew install ansible@2.2"
