### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-vagrant#8]
@joemaller - thanks for the talk last night. I'm excited to dive into vagrant and this solution has me up in running is seconds.

Unfortunately, as I'm attempting to pull a live site into this local dev environment I am getting a timeout. Mainly because the database is fairly massive. Is it possible to adjust the php settings? 

```
FATAL PHP ERROR: type => 1 message => Maximum execution time of 30 seconds exceeded file => /vagrant/site/importbuddy/lib/zipbuddy/zbzipziparchive.php line => 97
```

A little more info about the error source. I'm using [Backup Buddy](https://ithemes.com/purchase/backupbuddy/) and it requires two files:
- importbuddy.php - all the heavy lifting
- backupbuddyarchive.zip - site archive (can include database and/or files)

**Comment by joemaller** [comment]
This was one of the things I took away from Steve's talk. I'll have it added to the base box very soon.

**Comment by jgraup** [comment]
Great, I'll be looking forward to it.

For the record I did manage to get around this issue by placing a couple lines in the offending php file just now:

``` php
 ini_set('max_execution_time', 300); // 300 seconds = 5 minutes
 set_time_limit(0);
```

Aside from that small hiccup, the whole process has been seamless and smooth. Thanks again!

**Comment by joemaller** [comment]
This should be resolved, you'll need to update the vagrant box by running `vagrant box update` before `vagrant up`.

![image](https://cloud.githubusercontent.com/assets/8320/11280959/68716390-8ec6-11e5-9e79-fc82c1e82066.png)
